"""add oauth_id to user

Revision ID: be51df96557a
Revises: e6bb583aac2d
Create Date: 2025-09-25 02:47:11.149272

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be51df96557a"
down_revision: str | None = "e6bb583aac2d"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oauth_id", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_oauth_id"), ["oauth_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_oauth_id"))
        batch_op.drop_column("oauth_id")

    # ### end Alembic commands ###
