name: E2E Tests
on:
  pull_request:
    branches:
      - mealie-next
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/e2e
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      if: always()
      with:
        path: prime
        key: ${{ runner.os }}-cache
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build Image
      run: docker compose build
      working-directory: ./tests/e2e/docker
    - name: Deploy Test Environment
      run: docker compose up -d
      working-directory: ./tests/e2e/docker
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Check test environment
      run: docker ps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - name: Destroy Test Environment
      if: always()
      run: docker compose down --volumes
      working-directory: ./tests/e2e/docker
